name: 🚀 New feature
description: Propose a new feature.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear and concise description of the current behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested Behavior
      description: |
        A clear and concise description of the suggested behavior.
        Add any other context about the enhancement here. If applicable, add screenshots/screen records or links to help explain.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: What is the motivation / use case for changing the behavior?
  - type: textarea
    attributes:
      label: Potential risks
      description: Have you identified any potential risks or conflicts? Both technical and practical are of interest.
